### PR TITLE
Web reg proto dtype

### PR DESCRIPTION
**Pull request by ganqqwerty**
Added back the data type, modifieed the protocol field to the webregistration schema

### CODE REVIEW

**Comment by lomigmegard** [comment]
@ganqqwerty This schema has to be renamed to `SingleActivityMetadata`.

**Comment by ganqqwerty** [comment]
@tarfaa updated

**Comment by cathzwah** [comment]
For contributors the organisation field only contains the high level organisation such as "Ecole Polytechnique Fédérale de Lausanne".
The laboratory or institute should also be captured. Add a field "institute" (not mandatory) as per our discussion earlier this week

**Comment by cathzwah** [comment]
The field 
                "lab": {
                    "type": "string",
                    "description": "The sub-entity within an organisation, e.g. Blue Brain Project within EPFL"
                }

should be part of the Contributor object, not organisation. The UUID in the definition.organisation correspond to "EPFL", not "BBP, EPFL".

Cheers

**Comment by samuel-kerrien** [comment]
Yuri, can you take a look at the pull request #9 and merge into your the changes I made around the javaType parameters please ? Then we can abandon my pull request.

**Pull request closed without merging**
