### PR TITLE
+dataset.methods in sam

### PR DESCRIPTION
**Pull request by ganqqwerty**

### CODE REVIEW

**Comment by lomigmegard** [comment]
the comment should be in the other CHANGELOG

**Comment by lomigmegard** [comment]
Also, will this require some changes in the Java converter? If yes, please create a ticket assigned to me with a short description.

**Comment by samuel-kerrien** [comment]
Looks good to me, not sure if Yuri has addressed Lomig's comments though ... Yuri, can you confirm so I can merge ?

**Comment by ganqqwerty** [comment]
yes, moved a message to different changelog

**Pull request merged**
