### PR TITLE
representations: +satellite files. resourses:  +evidences. files: more than one address

### PR DESCRIPTION
**Pull request by ganqqwerty**
Added support for the satellite files and brought back the evidences.

### CODE REVIEW

**Comment by ganqqwerty** [comment]
howdy, it's ready!

**Comment by cathzwah** [comment]
Looks good to me.

**Comment by MFSY** [comment]
look good to me

**Comment by ganqqwerty** [comment]
@samuel-kerrien have a look, if looks good to you, we're gonna merge it

**Comment by ganqqwerty** [comment]
I'm happy now. @samuel-kerrien @cathzwah @MFSY

**Pull request merged**
